### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by matthiaskoenig** [combine-org/combine-notebooks#13]
Support for python 3.11.

**Comment by pgleeson** [comment]
Integrated into tests

**Comment by pgleeson** [comment]
Actuall this needs to be put in tox config...
https://github.com/combine-org/combine-notebooks/blob/a59e224a29955c80b4ed2fe1e78fed022982b96e/tox.ini#L8

**Comment by pgleeson** [comment]
Looks like it is being tested with py 3.11 after all... https://github.com/combine-org/combine-notebooks/actions/runs/5949649839/job/16135850180
