### ISSUE TITLE
Add/adapt NeuroML examples

### ISSUE THREAD

**Issue by pgleeson** [combine-org/combine-notebooks#3]
FYI @matthiaskoenig there are a number of NeuroML based notebooks [here](https://github.com/NeuroML/Documentation/tree/master/source/Userdocs/NML2_examples) e.g. https://github.com/NeuroML/Documentation/blob/master/source/Userdocs/NML2_examples/SingleNeuron.ipynb.

These have been incorporated into the JupyterBooks based NeuroML documentation, https://docs.neuroml.org/Userdocs/NML2_examples/SingleNeuron.html, which allows them to be mixed in with other documentation pages, as well as links added for running the notebooks on Binder, Google Colab etc.

NeuroML examples are probably further down the line, especially if you want to concentrate on the repressilator model, but it might be nice to add some examples of other standards and different models too, and JupyterBook is a really nice way to package them up into an interactive guide.

**Comment by matthiaskoenig** [comment]
@pgleeson Thanks. This is great. The idea is to link to such additional information from the notebooks.

**Comment by pgleeson** [comment]
Basic example added at: https://github.com/combine-org/combine-notebooks/blob/main/notebooks/neuroml.ipynb
